# Generated by Django 3.2.6 on 2021-09-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FiruzaIslam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daughter1', models.CharField(max_length=50)),
                ('daughter2', models.CharField(max_length=50)),
                ('daughter3', models.CharField(max_length=50)),
                ('daughter4', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NorulIslam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('son1', models.CharField(max_length=50)),
                ('son2', models.CharField(max_length=50)),
                ('son3', models.CharField(max_length=50)),
                ('son4', models.CharField(max_length=50)),
            ],
        ),
    ]
